name: Automated Test Cases
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          gunzip all_genes_info.json.gz
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: python BOCC/test_BOCC.py
